#!/bin/bash
#
# 1-indicator_triage.sh
#
# MedDefense Health Systems -- Intelligence-Driven Defense (Task 1: Signal
# vs Noise)
#
# Purpose
#   Reads the consolidated, deduplicated indicator list produced by Task 0
#   (0-intel_intake.py / consolidated_indicators.json) and classifies each
#   indicator as ACTIONABLE, CONTEXTUAL or NOISE, joining in the commercial
#   feed's own confidence score, tags and analyst notes
#   (commercial_feed_extract.json) wherever available.
#
#   The category, confidence level, uncertainty flag and one-line
#   justification for every indicator are analyst judgment recorded in
#   triage_data.tsv (not derived by a generic rule), because a threshold
#   alone cannot decide, for example, that a domain is sinkholed, that a
#   hash string is one byte short of a valid SHA-256, or that a URL is a
#   placeholder template rather than a literal indicator. This script's
#   job is to join that judgment against the source data, verify nothing
#   has drifted since Task 0, print a readable report and compute the
#   summary statistics -- not to invent the judgment itself.
#
# Materials
#   consolidated_indicators.json  (regenerated fresh from 0-intel_intake.py)
#   commercial_feed_extract.json
#   triage_data.tsv                (this task's analyst judgment table)
#
# Usage
#   ./1-indicator_triage.sh
#
# Output
#   Prints the full triage report to stdout and writes it to
#   1-indicator_triage.md.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

INTAKE_SCRIPT="0-intel_intake.py"
CONSOLIDATED_JSON="consolidated_indicators.json"
COMMERCIAL_JSON="commercial_feed_extract.json"
TRIAGE_TSV="triage_data.tsv"
OUTFILE="1-indicator_triage.md"

for f in "${INTAKE_SCRIPT}" "${COMMERCIAL_JSON}" "${TRIAGE_TSV}"; do
    if [[ ! -f "${f}" ]]; then
        echo "ERROR: required file not found: ${f}" >&2
        exit 1
    fi
done

command -v jq >/dev/null 2>&1 || { echo "ERROR: jq is required." >&2; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "ERROR: python3 is required." >&2; exit 1; }

# -----------------------------------------------------------------------
# 1. Regenerate the consolidated indicator list fresh from Task 0, so
#    this triage always runs against the current source files rather
#    than a stale cached JSON.
# -----------------------------------------------------------------------
echo "Regenerating ${CONSOLIDATED_JSON} from ${INTAKE_SCRIPT} ..." >&2
python3 "${INTAKE_SCRIPT}" >/tmp/0-intel_intake.regen.log 2>&1 || {
    echo "ERROR: ${INTAKE_SCRIPT} failed; see /tmp/0-intel_intake.regen.log" >&2
    exit 1
}

if [[ ! -f "${CONSOLIDATED_JSON}" ]]; then
    echo "ERROR: ${CONSOLIDATED_JSON} was not produced by ${INTAKE_SCRIPT}" >&2
    exit 1
fi

# -----------------------------------------------------------------------
# 2. Drift check: every (type,value) in triage_data.tsv must exist in
#    the freshly regenerated consolidated list, and vice versa. If Task
#    0's source files or dedup logic change later, this catches it
#    instead of silently triaging a stale list.
# -----------------------------------------------------------------------
missing_from_triage=$(jq -r '.[] | "\(.type)\t\(.value)"' "${CONSOLIDATED_JSON}" \
    | sort -u > /tmp/consolidated_keys.txt
    tail -n +2 "${TRIAGE_TSV}" | cut -f1,2 | sort -u > /tmp/triage_keys.txt
    comm -23 /tmp/consolidated_keys.txt /tmp/triage_keys.txt)

extra_in_triage=$(comm -13 /tmp/consolidated_keys.txt /tmp/triage_keys.txt)

if [[ -n "${missing_from_triage}" || -n "${extra_in_triage}" ]]; then
    echo "WARNING: triage_data.tsv has drifted from ${CONSOLIDATED_JSON}." >&2
    [[ -n "${missing_from_triage}" ]] && echo "  In Task 0 but not triaged: ${missing_from_triage}" >&2
    [[ -n "${extra_in_triage}" ]] && echo "  Triaged but not in Task 0: ${extra_in_triage}" >&2
fi

CONSOLIDATED_COUNT=$(jq 'length' "${CONSOLIDATED_JSON}")
TRIAGE_COUNT=$(($(wc -l < "${TRIAGE_TSV}") - 1))

# -----------------------------------------------------------------------
# 3. Build the report.
# -----------------------------------------------------------------------
{
    echo "1 - Indicator Triage"
    echo
    echo "MedDefense Health Systems -- Intelligence-Driven Defense (4x02)"
    echo "Task 1: triaging the consolidated Task 0 indicator list into ACTIONABLE, CONTEXTUAL or NOISE, with a documented justification, confidence level and uncertainty flag for every indicator."
    echo "Generated by \`1-indicator_triage.sh\`, which regenerates \`${CONSOLIDATED_JSON}\` from \`${INTAKE_SCRIPT}\` on every run and joins it against \`${COMMERCIAL_JSON}\` and the analyst judgment recorded in \`${TRIAGE_TSV}\`."
    echo
    echo "Consolidated indicators from Task 0: ${CONSOLIDATED_COUNT}. Indicators triaged: ${TRIAGE_COUNT}."
    if [[ -n "${missing_from_triage}" || -n "${extra_in_triage}" ]]; then
        echo
        echo "> **Drift warning:** the triage table and the freshly regenerated Task 0 output do not match exactly (see stderr from this run). Re-run \`1-indicator_triage.sh\` after updating \`triage_data.tsv\` if Task 0's source files change."
    fi
    echo
    echo "> **Note on the indicator count:** Task 0's own deliverable (\`0-intel_intake.md\`) documents that this script's reproducible, exact-match deduplication of the four official source files yields ${CONSOLIDATED_COUNT} unique indicators, not the lab's stated reference of 64 -- verified against the official materials zip and left open with the course staff. This task triages the ${CONSOLIDATED_COUNT} indicators actually produced by that reproducible pipeline; the ACTIONABLE/CONTEXTUAL/NOISE judgment below does not depend on which of the two counts is eventually confirmed correct."
    echo
    echo "---"
    echo
    echo "## Per-Indicator Triage"
    echo

    printf "%s\n" "| Type | Value | Source(s) | Category | Confidence | Uncertainty | Justification |"
    printf "%s\n" "|---|---|---|---|---|---|---|"

    tail -n +2 "${TRIAGE_TSV}" | while IFS=$'\t' read -r itype value category confidence uncertainty justification; do
        # look up provenance from the freshly regenerated consolidated list
        sources=$(jq -r --arg t "${itype}" --arg v "${value}" \
            '.[] | select(.type == $t and .value == $v) | .sources | join(", ")' \
            "${CONSOLIDATED_JSON}")

        # look up the commercial feed's own confidence/note, if this
        # indicator was reported there (type "hash" -> feed's "sha256")
        feed_type="${itype}"
        [[ "${itype}" == "hash" ]] && feed_type="sha256"
        acme_conf=$(jq -r --arg t "${feed_type}" --arg v "${value}" \
            '.indicators[] | select(.type == $t and .value == $v) | .acme_confidence' \
            "${COMMERCIAL_JSON}")

        conf_display="${confidence}"
        if [[ -n "${acme_conf}" ]]; then
            conf_display="${confidence} (Acme conf. ${acme_conf})"
        fi

        printf "| %s | \`%s\` | %s | %s | %s | %s | %s |\n" \
            "${itype}" "${value}" "${sources}" "${category}" "${conf_display}" "${uncertainty}" "${justification}"
    done

    echo
    echo "---"
    echo
    echo "## Summary Statistics"
    echo

    total="${TRIAGE_COUNT}"
    actionable=$(tail -n +2 "${TRIAGE_TSV}" | awk -F'\t' '$3=="ACTIONABLE"' | wc -l)
    contextual=$(tail -n +2 "${TRIAGE_TSV}" | awk -F'\t' '$3=="CONTEXTUAL"' | wc -l)
    noise=$(tail -n +2 "${TRIAGE_TSV}" | awk -F'\t' '$3=="NOISE"' | wc -l)
    uncertain=$(tail -n +2 "${TRIAGE_TSV}" | awk -F'\t' '$5=="YES"' | wc -l)

    pct() { awk -v n="$1" -v d="$2" 'BEGIN{printf "%.1f", (d>0)? (n/d*100) : 0}'; }

    echo "1. Total indicators reviewed: ${total}"
    echo "2. ACTIONABLE: ${actionable} ($(pct "${actionable}" "${total}")%)"
    echo "3. CONTEXTUAL: ${contextual} ($(pct "${contextual}" "${total}")%)"
    echo "4. NOISE: ${noise} ($(pct "${noise}" "${total}")%)"
    echo "5. Flagged with an uncertainty marker (category not straightforward): ${uncertain} ($(pct "${uncertain}" "${total}")%)"
    echo
    echo "### Top reasons indicators were downgraded to NOISE or CONTEXTUAL"
    echo
    echo "Counted from the justification text of every NOISE/CONTEXTUAL row:"
    echo
    downgraded=$(tail -n +2 "${TRIAGE_TSV}" | awk -F'\t' '$3=="NOISE" || $3=="CONTEXTUAL"')
    shared_count=$(echo "${downgraded}" | grep -Eic "shared|cdn|cloud|cloudflare" || true)
    clustering_count=$(echo "${downgraded}" | grep -ic "cluster" || true)
    template_count=$(echo "${downgraded}" | grep -Eic "placeholder|template" || true)
    sinkhole_count=$(echo "${downgraded}" | grep -ic "sinkhol" || true)
    unrelated_count=$(echo "${downgraded}" | grep -ic "unrelated" || true)
    echo "- Shared/CDN/cloud-provider infrastructure (would cause broad false positives if blocked): ${shared_count}"
    echo "- ML similarity-clustering only, no human corroboration: ${clustering_count}"
    echo "- Placeholder/template value, not a literal indicator: ${template_count}"
    echo "- Domain sinkholed / no longer live: ${sinkhole_count}"
    echo "- Explicitly tagged as an unrelated malware cluster: ${unrelated_count}"
    echo
    echo "### Top indicators recommended for immediate detection"
    echo
    echo "ACTIONABLE indicators with HIGH confidence, ranked by source corroboration (most-corroborated first):"
    echo
    tail -n +2 "${TRIAGE_TSV}" | awk -F'\t' '$3=="ACTIONABLE" && $4=="HIGH"' | while IFS=$'\t' read -r itype value category confidence uncertainty justification; do
        sources=$(jq -r --arg t "${itype}" --arg v "${value}" \
            '.[] | select(.type == $t and .value == $v) | .sources | length' \
            "${CONSOLIDATED_JSON}")
        echo "${sources}	${itype}	${value}"
    done | sort -t$'\t' -k1,1 -rn | head -10 | awk -F'\t' '{printf "- (%s source%s) %s: `%s`\n", $1, ($1==1?"":"s"), $2, $3}'

} > "${OUTFILE}"

cat "${OUTFILE}"
echo
echo "Written: ${OUTFILE}" >&2
