/*
 * 9-yara_phishing_pdf.yar
 *
 * MedDefense Health Systems -- Intelligence-Driven Defense (4x02)
 * Task 9: YARA Foundations
 *
 * Detects PDF lure documents matching the HEALTHBANE phishing-kit
 * pattern, as identified during the 4x00 investigation: a single-page
 * PDF generated by wkhtmltopdf 0.12.6, containing embedded /URI links
 * to credential-harvesting infrastructure.
 *
 * Evidence basis (verified directly against the sample files, not
 * assumed): both positive samples (phishing_sample.pdf,
 * healthbane_lure_02.pdf) carry the string "wkhtmltopdf 0.12.6" in
 * their PDF /Producer metadata, plus two /URI link annotations whose
 * paths contain credential-harvesting keywords ("/verify", "/login",
 * "/portal") and query parameters ("id=", "token="). Both negative
 * samples (clean_invoice.pdf, benign_invoice.pdf) were produced by
 * unrelated, legitimate tools (Adobe PDF Library 23.0 / Adobe InDesign
 * 18.2, and Microsoft Print To PDF / Word 2019 respectively) and each
 * contains only a single, non-credential-harvesting /URI link.
 */

rule HEALTHBANE_Phishing_PDF
{
    meta:
        author         = "milly.dulee@gmail.com"
        description    = "Detects HEALTHBANE phishing-kit PDF lures generated with wkhtmltopdf and containing credential-harvesting link patterns"
        date           = "2026-09-29"
        reference       = "MedDefense 4x00 incident investigation - HEALTHBANE campaign, Email 5 PDF attachment analysis"
        threat_level   = "high"
        confidence     = "medium"
        // "medium" and not "high": the rule is built from a small, project-provided
        // sample corpus (2 positives / 2 negatives). It has not been validated
        // against a large, diverse real-world PDF population, so its false-positive
        // rate on unrelated wkhtmltopdf-generated documents (a legitimate use case
        // for that tool) in the wild is unknown.

    strings:
        // PDF magic bytes -- every valid PDF file starts with this header.
        // Used as a fast, mandatory file-type gate before any other check runs.
        $pdf_magic = "%PDF" ascii

        // The tooling fingerprint identified in the 4x00 investigation: the
        // HEALTHBANE kit's lure PDFs are rendered server-side with
        // wkhtmltopdf 0.12.6 rather than a standard office/PDF authoring tool.
        // This single string is what separates both positive samples from both
        // negative samples in the /Producer metadata field.
        $wkhtmltopdf = "wkhtmltopdf" ascii

        // Credential-harvesting URL path fragments. Each of these appears in
        // at least one confirmed HEALTHBANE domain path
        // (meddefense-portal.com/verify/staff, .../portal/login,
        // medequip-supplies.net/portal/login). "/enroll" is included per the
        // task's own required pattern list even though it was not observed in
        // this particular sample pair, since the campaign's broader domain set
        // (per Task 2/7 sourcing) is not limited to these two samples alone.
        $path_verify = "/verify" ascii nocase
        $path_login  = "/login" ascii nocase
        $path_portal = "/portal" ascii nocase
        $path_enroll = "/enroll" ascii nocase

        // URL query parameters used by the kit to track/pass victim identity
        // and a per-target session token back to the credential-harvesting
        // backend (observed literally in phishing_sample.pdf:
        // "id=dmarsh&token=a8f3e2d1").
        $param_token = "token=" ascii nocase
        $param_id    = "id=" ascii nocase

        // Campaign-related domain fragments. Both confirmed-malicious domains
        // used in this sample set share the literal substring "med" combined
        // with a healthcare-adjacent second element and are registered outside
        // MedDefense's real corporate domain (meddefense.com, note no hyphen) --
        // this is a narrow, single-word-boundary marker, not a broad wildcard.
        $domain_1 = "meddefense-portal.com" ascii nocase
        $domain_2 = "medequip-supplies.net" ascii nocase

    condition:
        // 1. Must be a genuine PDF file (magic bytes at the very start of file).
        $pdf_magic at 0
        and
        (
            // 2. Must show the wkhtmltopdf tooling fingerprint (strong signal
            //    on its own, since neither negative sample uses this tool) ...
            $wkhtmltopdf
            or
            // ... OR carry a directly-confirmed campaign domain, in case a
            // future sample is regenerated with a different renderer but
            // still points at known HEALTHBANE infrastructure.
            any of ($domain_*)
        )
        and
        (
            // 3. Must contain at least two distinct credential-harvesting
            //    URL-pattern hits (path keywords and/or query parameters
            //    combined), per the task's explicit requirement. A single
            //    hit alone is not sufficient: clean_invoice.pdf's only link
            //    ("/vendor/statements") and benign_invoice.pdf's only link
            //    ("/billing/statements") match none of these strings, but a
            //    >=2 threshold keeps the rule from firing on a single
            //    coincidental substring match in an unrelated document.
            (
                (#path_verify + #path_login + #path_portal + #path_enroll
                 + #param_token + #param_id) >= 2
            )
        )
}

/*
 * --- Test results (yara 4.5.0, run against threat_detection/4x02_.../samples/) ---
 *
 * $ yara 9-yara_phishing_pdf.yar samples/
 * HEALTHBANE_Phishing_PDF samples/phishing_sample.pdf
 * HEALTHBANE_Phishing_PDF samples/healthbane_lure_02.pdf
 *
 * True positives  (2/2): phishing_sample.pdf, healthbane_lure_02.pdf both
 *   matched -- each hits $pdf_magic, $wkhtmltopdf, its campaign domain
 *   string, and 3-5 credential-harvesting path/parameter strings (well
 *   above the required >=2 threshold), confirmed with `yara -s`.
 *
 * True negatives (2/2): clean_invoice.pdf, benign_invoice.pdf both
 *   produced no match -- neither file contains "wkhtmltopdf" (they were
 *   produced by Adobe PDF Library / Adobe InDesign and Microsoft Print
 *   To PDF, respectively), neither contains a HEALTHBANE campaign
 *   domain string, and each file's single /URI link
 *   ("/vendor/statements", "/billing/statements") matches none of the
 *   credential-harvesting path/parameter strings, so the >=2 threshold
 *   is never reached.
 *
 * Result: 0 false positives, 0 false negatives against this sample set.
 */
