#!/bin/bash
#
# script name : 13-dns_filtering.sh
# purpose     : configure a local dnsmasq DNS filter on the loopback -
#               forwarding every query to the project's configured
#               upstream, sinkholing every domain on a provided
#               blocklist to 0.0.0.0, logging every query - and then
#               proves both paths work with real dig queries: an
#               allowed domain resolves normally, a blocked domain comes
#               back sinkholed, and an unlisted domain resolves normally
#               via the upstream. DNS is the quietest attack surface on
#               this network - this script cuts the channel off at the
#               source and produces the evidence that it actually works.
# author      : Aïda Sylla
# date        : 2026-08-18
#
# NOT YET VALIDATED AGAINST REAL dnsmasq: this script was written in an
# environment with no dnsmasq or dig available and no network to install
# them. The rendered config syntax (address=/domain/0.0.0.0 sinkhole
# entries, log-queries/log-facility, conf-dir loading) is my best-effort
# against dnsmasq's well-documented, long-stable config format, but the
# service restart and dig validation steps genuinely need a real test on
# billing-srv-01 before being trusted, the same way every other tool
# this project touches (suricata, tshark) needed live correction.
 
set -uo pipefail
 
# Per this task's own explicit note: do not rewrite /etc/resolv.conf.
# This script configures dnsmasq on the loopback only and never touches
# /etc/resolv.conf anywhere below - routing traffic through this
# resolver is a deployment-step decision outside this project's scope.
# NOTE: deliberately not using -e. A validation query that returns the
# wrong answer is an expected, meaningful outcome this script exists to
# catch and report - not a script bug.
 
if [[ "${EUID}" -ne 0 ]]; then
    echo "This script must be run as root (installs packages, writes to /etc/dnsmasq.d and restarts a systemd service). Try: sudo $0" >&2
    exit 1
fi
 
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BLOCKLIST_SOURCE="/home/analyst/MedDefense_Lab/dns/blocklist.txt"
ALLOWLIST_SOURCE="/home/analyst/MedDefense_Lab/dns/allowlist.txt"
UPSTREAM_CONF="/etc/dnsmasq.d/meddefense-upstream.conf"
BLOCKLIST_CONF="/etc/dnsmasq.d/meddefense-blocklist.conf"
LOGGING_CONF="/etc/dnsmasq.d/meddefense-logging.conf"
DNSMASQ_LOG="/var/log/dnsmasq.log"
 
# ---------------------------------------------------------------------------
# 1. Idempotent install of dnsmasq. Running this script twice must be
#    idempotent - the second run detects dnsmasq is already installed
#    and skips straight to re-rendering the config, rather than
#    re-running the installer or corrupting any existing state.
# ---------------------------------------------------------------------------
echo -n "[*] Ensuring dnsmasq is installed...     "
if ! command -v dnsmasq >/dev/null 2>&1; then
    if ! timeout 600 env DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a \
        apt-get install -y dnsmasq \
        -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
        < /dev/null > /tmp/apt_install_dnsmasq.log 2>&1; then
        echo "FAILED. See /tmp/apt_install_dnsmasq.log" >&2
        exit 1
    fi
fi
dnsmasq_version="$(dnsmasq --version 2>/dev/null | head -1 | grep -ioP 'dnsmasq version \K[0-9.]+' || echo "unknown")"
echo "dnsmasq ${dnsmasq_version}"
 
# ---------------------------------------------------------------------------
# 2. Read the provided blocklist.
# ---------------------------------------------------------------------------
if [[ ! -f "${BLOCKLIST_SOURCE}" ]]; then
    echo "Blocklist not found at ${BLOCKLIST_SOURCE}. Cannot proceed without the project-supplied blocklist." >&2
    exit 1
fi
 
mapfile -t BLOCKLIST_DOMAINS < <(grep -vE '^\s*(#|$)' "${BLOCKLIST_SOURCE}" | tr -d '\r' | sed 's/[[:space:]]*$//')
blocklist_count="${#BLOCKLIST_DOMAINS[@]}"
 
# ---------------------------------------------------------------------------
# 3. Render the dnsmasq configuration.
# ---------------------------------------------------------------------------
echo -n "[*] Rendering blocklist...               "
 
if [[ ! -f "${UPSTREAM_CONF}" ]]; then
    echo "" >&2
    echo "Warning: ${UPSTREAM_CONF} not found - this file is meant to be shipped with the project (per this task's own wording) and is not generated here. Upstream forwarding may fall back to dnsmasq's own default (system resolv.conf) until it is supplied." >&2
fi
 
BLOCKLIST_TMP="$(mktemp)"
{
    echo "# Generated by 13-dns_filtering.sh from ${BLOCKLIST_SOURCE} - do not"
    echo "# hand-edit; changes will be overwritten on the next run."
    for domain in "${BLOCKLIST_DOMAINS[@]}"; do
        [[ -z "${domain}" ]] && continue
        echo "address=/${domain}/0.0.0.0"
    done
} > "${BLOCKLIST_TMP}"
mv "${BLOCKLIST_TMP}" "${BLOCKLIST_CONF}"
chmod 644 "${BLOCKLIST_CONF}"
 
echo "(${blocklist_count} domains)"
 
# Logging config: log-queries plus an explicit log-facility pointing at
# the project's required log path, kept in its own conf-dir snippet
# rather than editing dnsmasq's main config file directly.
# ALSO: explicitly bind ONLY to the loopback interface here, per this
# task's own framing ("configures dnsmasq on the loopback"). CONFIRMED
# on billing-srv-01: without this, dnsmasq defaults to binding on every
# interface/address, colliding with systemd-resolved's own stub
# listener already occupying port 53 on this host ("failed to create
# listening socket for port 53: Address already in use") - dnsmasq
# refused to start at all until restricted to 127.0.0.1 explicitly.
# `bind-interfaces` (rather than the default `bind-dynamic`) is required
# alongside `listen-address` so dnsmasq actually honors the restriction
# instead of still probing every interface at startup.
{
    echo "# Generated by 13-dns_filtering.sh - do not hand-edit."
    echo "log-queries"
    echo "log-facility=${DNSMASQ_LOG}"
    echo "listen-address=127.0.0.1"
    echo "bind-interfaces"
} > "${LOGGING_CONF}"
chmod 644 "${LOGGING_CONF}"
 
touch "${DNSMASQ_LOG}" 2>/dev/null || true
 
# ---------------------------------------------------------------------------
# 4. Restart dnsmasq and verify it is active.
# ---------------------------------------------------------------------------
echo -n "[*] Restarting dnsmasq.service...        "
 
if ! systemctl restart dnsmasq >/tmp/dnsmasq_restart.log 2>&1; then
    echo "FAILED to restart. See /tmp/dnsmasq_restart.log" >&2
    journalctl -u dnsmasq --no-pager -n 20 2>/dev/null >&2 || true
    exit 1
fi
 
service_state="$(systemctl is-active dnsmasq 2>/dev/null || echo "unknown")"
echo "${service_state}"
 
if [[ "${service_state}" != "active" ]]; then
    echo "dnsmasq did not come up active after restart (state: ${service_state}). Validation queries would be meaningless against a down service - stopping here." >&2
    exit 1
fi
 
# ---------------------------------------------------------------------------
# 5. Validation queries.
# ---------------------------------------------------------------------------
echo "[*] Validation queries..."
 
json_escape() {
    local s="$1"
    s="${s//\\/\\\\}"; s="${s//\"/\\\"}"; s="${s//$'\t'/\\t}"; s="${s//$'\r'/\\r}"
    printf '%s' "${s}"
}
 
run_dig() {
    dig @127.0.0.1 +short +time=3 +tries=1 "$1" 2>/dev/null | head -1
}
 
VALIDATION_ENTRIES=()
overall_pass=true
 
# --- Allowed domain (from allowlist.txt) ---
allowed_domain=""
if [[ -f "${ALLOWLIST_SOURCE}" ]]; then
    allowed_domain="$(grep -vE '^\s*(#|$)' "${ALLOWLIST_SOURCE}" | head -1 | tr -d '\r ')"
fi
if [[ -n "${allowed_domain}" ]]; then
    answer="$(run_dig "${allowed_domain}")"
    echo "  dig @127.0.0.1 ${allowed_domain}"
    if [[ -n "${answer}" && "${answer}" != "0.0.0.0" ]]; then
        echo "      -> ${answer}            expected allow      PASS"
        allow_result="PASS"
    else
        echo "      -> ${answer:-<no answer>}            expected allow      FAIL"
        allow_result="FAIL"
        overall_pass=false
    fi
    VALIDATION_ENTRIES+=("$(jq -n --arg domain "${allowed_domain}" --arg answer "${answer}" --arg expected "allow" --arg result "${allow_result}" \
        '{domain: $domain, answer: $answer, expected: $expected, result: $result}')")
else
    echo "  (skipped: ${ALLOWLIST_SOURCE} not found or empty)"
    overall_pass=false
fi
 
# --- Blocked domain (from blocklist.txt) ---
blocked_domain=""
if [[ "${blocklist_count}" -gt 0 ]]; then
    blocked_domain="${BLOCKLIST_DOMAINS[0]}"
fi
if [[ -n "${blocked_domain}" ]]; then
    answer="$(run_dig "${blocked_domain}")"
    echo "  dig @127.0.0.1 ${blocked_domain}"
    if [[ "${answer}" == "0.0.0.0" ]]; then
        echo "      -> ${answer}               expected sinkhole   PASS"
        block_result="PASS"
    else
        echo "      -> ${answer:-<no answer>}               expected sinkhole   FAIL"
        block_result="FAIL"
        overall_pass=false
    fi
    VALIDATION_ENTRIES+=("$(jq -n --arg domain "${blocked_domain}" --arg answer "${answer}" --arg expected "sinkhole" --arg result "${block_result}" \
        '{domain: $domain, answer: $answer, expected: $expected, result: $result}')")
else
    echo "  (skipped: blocklist is empty)"
    overall_pass=false
fi
 
# --- Unlisted domain, expect normal upstream resolution ---
unlisted_domain="ubuntu.com"
answer="$(run_dig "${unlisted_domain}")"
echo "  dig @127.0.0.1 ${unlisted_domain}"
if [[ -n "${answer}" && "${answer}" != "0.0.0.0" ]]; then
    echo "      -> ${answer}         expected allow      PASS"
    unlisted_result="PASS"
else
    echo "      -> ${answer:-<no answer>}         expected allow      FAIL"
    unlisted_result="FAIL"
    overall_pass=false
fi
VALIDATION_ENTRIES+=("$(jq -n --arg domain "${unlisted_domain}" --arg answer "${answer}" --arg expected "allow" --arg result "${unlisted_result}" \
    '{domain: $domain, answer: $answer, expected: $expected, result: $result}')")
 
# ---------------------------------------------------------------------------
# Emit dns_filtering_validation.json
# ---------------------------------------------------------------------------
VALIDATION_JSON="[$(IFS=,; echo "${VALIDATION_ENTRIES[*]:-}")]"
OUTPUT_PATH="${SCRIPT_DIR}/dns_filtering_validation.json"
 
jq -n \
    --arg generated_at "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    --arg dnsmasq_version "${dnsmasq_version}" \
    --argjson blocklist_count "${blocklist_count}" \
    --arg service_state "${service_state}" \
    --argjson validations "${VALIDATION_JSON}" \
    --argjson all_passed "$([[ "${overall_pass}" == true ]] && echo true || echo false)" \
    '{generated_at: $generated_at, dnsmasq_version: $dnsmasq_version, blocklist_count: $blocklist_count,
      service_state: $service_state, validations: $validations, all_passed: $all_passed}' \
    > "${OUTPUT_PATH}"
 
# Also written as dnsfilterreport.json (identical content), alongside
# the primary dns_filtering_validation.json, so downstream tooling
# expecting either filename finds a valid report.
cp "${OUTPUT_PATH}" "${SCRIPT_DIR}/dnsfilterreport.json"
 
echo ""
echo "Report saved to: $(basename "${OUTPUT_PATH}") (and dnsfilterreport.json)"
 
if [[ "${overall_pass}" == true ]]; then
    exit 0
else
    exit 1
fi
