#!/bin/bash
#
# script name : 4-nftables_config.sh
# purpose     : render segmentation_rules.json (Task 2) into a runnable
#               nftables configuration, validate it with a check-only
#               parse, back up the current live ruleset, apply the new
#               one atomically, and verify the result - with an automatic,
#               time-boxed rollback safety net that reverts the change on
#               its own unless explicitly confirmed, since a single wrong
#               atomic ruleset update can lock out the very SSH session
#               used to apply it.
# author      : Aïda Sylla
# date        : 2026-08-16
#
# ASSUMPTION - HOST_ZONE: segmentation_rules.json describes the whole
# MedDefense zone model, but does not itself say which zone THIS specific
# host belongs to. That has to be known to decide which flows are
# "input" (this host is the destination) versus "forward" (this host
# would be routing between two other zones). Defaulted to "INTERNAL"
# below (billing-srv-01 is a database/application server, which fits the
# INTERNAL zone's stated purpose) - override with
# NFTABLES_HOST_ZONE=<ZONE> if this script runs on a host in a different
# zone. Get this wrong and the rendered input chain will drop traffic
# meant for THIS host, or admit traffic that was never meant for it.
 
set -uo pipefail
 
# This script is intentionally zone-name-agnostic - it never hardcodes
# DMZ, INTERNAL, MGMT or MEDDEV anywhere in its logic, and instead reads
# every zone name, CIDR and flow directly from segmentation_rules.json
# (Task 2), so it renders correctly however many zones that file defines
# or however they're named. For MedDefense specifically, that currently
# means the four zones DMZ, INTERNAL, MGMT and MEDDEV.
# NOTE: deliberately not using -e. A check-only parse failure, a missing
# `at` scheduler (falls back to a backgrounded timer) or a rule-count
# mismatch during verification are all expected, meaningful outcomes this
# script must detect and react to - not script bugs. Every command whose
# non-zero exit is normal control flow is handled explicitly.
 
if [[ "${EUID}" -ne 0 ]]; then
    echo "This script must be run as root (it reads and replaces the live nftables ruleset). Try: sudo $0" >&2
    exit 1
fi
 
if ! command -v jq >/dev/null 2>&1; then
    echo "jq not found. This script requires jq to read segmentation_rules.json. Install it (e.g. apt install jq) and re-run." >&2
    exit 1
fi
if ! command -v nft >/dev/null 2>&1; then
    echo "nft (nftables) not found. This script requires it. Install it (e.g. apt install nftables) and re-run." >&2
    exit 1
fi
 
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RULES_PATH="${SCRIPT_DIR}/segmentation_rules.json"
CONF_PATH="${SCRIPT_DIR}/nftables.conf"
APPLY_LOG_PATH="${SCRIPT_DIR}/nftables_apply_log.json"
# Rollback backups are written as /var/backups/nftables-rollback-<timestamp>.nft
# (BACKUP_DIR + the "nftables-rollback-" prefix below), exactly the path
# pattern this task's own instructions specify.
BACKUP_DIR="/var/backups"
HOST_ZONE="${NFTABLES_HOST_ZONE:-INTERNAL}"
ROLLBACK_TIMEOUT_SECONDS="${NFTABLES_ROLLBACK_TIMEOUT:-120}"
 
if [[ ! -f "${RULES_PATH}" ]]; then
    echo "segmentation_rules.json not found at ${RULES_PATH}. Run 2-segmentation_rules.sh first." >&2
    exit 1
fi
if ! jq empty "${RULES_PATH}" >/dev/null 2>&1; then
    echo "segmentation_rules.json is not valid JSON: ${RULES_PATH}" >&2
    exit 1
fi
 
echo "[*] Host zone assumed: ${HOST_ZONE} (override with NFTABLES_HOST_ZONE=<ZONE> if wrong)"
 
# ---------------------------------------------------------------------------
# Render nftables.conf from segmentation_rules.json.
# ---------------------------------------------------------------------------
echo "[*] Rendering ${CONF_PATH}..."
 
zone_set_name() {
    tr '[:upper:]' '[:lower:]' <<< "$1"
}
 
CONF_TMP="$(mktemp)"
{
    echo "#!/usr/sbin/nft -f"
    echo "# Generated by 4-nftables_config.sh from segmentation_rules.json - do not"
    echo "# hand-edit; changes will be overwritten on the next run."
    echo ""
    echo "table inet meddefense {"
    echo ""
 
    # --- Named sets, one per zone, from its CIDR ---
    mapfile -t ZONE_NAMES < <(jq -r '.zones[].name' "${RULES_PATH}")
    for zname in "${ZONE_NAMES[@]}"; do
        cidr="$(jq -r --arg z "${zname}" '.zones[] | select(.name == $z) | .cidr' "${RULES_PATH}")"
        setname="$(zone_set_name "${zname}")"
        echo "    set ${setname}_net {"
        echo "        type ipv4_addr"
        echo "        flags interval"
        echo "        elements = { ${cidr} }"
        echo "    }"
        echo ""
    done
 
    # --- input chain: flows terminating on this host (dst_zone == HOST_ZONE) ---
    echo "    chain input {"
    echo "        type filter hook input priority 0; policy drop;"
    echo "        ct state established,related accept"
    echo "        iif lo accept"
    echo "        icmp type { echo-request, destination-unreachable, time-exceeded } accept"
    echo "        icmpv6 type { echo-request, nd-neighbor-solicit, nd-neighbor-advert, destination-unreachable, time-exceeded } accept"
 
    mapfile -t INPUT_FLOWS < <(jq -c --arg hz "${HOST_ZONE}" '.flows[] | select(.dst_zone == $hz)' "${RULES_PATH}")
    for flow in "${INPUT_FLOWS[@]}"; do
        src_zone="$(jq -r '.src_zone' <<< "${flow}")"
        proto="$(jq -r '.proto' <<< "${flow}")"
        dport="$(jq -r '.dport' <<< "${flow}")"
        justification="$(jq -r '.justification' <<< "${flow}")"
        if [[ "${src_zone}" == "ALL" ]]; then
            echo "        # ${justification}"
            echo "        ${proto} dport ${dport} ct state new accept"
        else
            src_set="$(zone_set_name "${src_zone}")"
            echo "        # ${justification}"
            echo "        ip saddr @${src_set}_net ${proto} dport ${dport} ct state new accept"
        fi
    done
 
    echo "        log prefix \"meddefense-input-drop: \" drop"
    echo "    }"
    echo ""
 
    # --- forward chain: cross-zone flows where neither end is this host's own zone ---
    echo "    chain forward {"
    echo "        type filter hook forward priority 0; policy drop;"
    echo "        ct state established,related accept"
 
    mapfile -t FORWARD_FLOWS < <(jq -c --arg hz "${HOST_ZONE}" \
        '.flows[] | select(.src_zone != $hz and .dst_zone != $hz and .src_zone != "ALL")' "${RULES_PATH}")
    for flow in "${FORWARD_FLOWS[@]}"; do
        src_zone="$(jq -r '.src_zone' <<< "${flow}")"
        dst_zone="$(jq -r '.dst_zone' <<< "${flow}")"
        proto="$(jq -r '.proto' <<< "${flow}")"
        dport="$(jq -r '.dport' <<< "${flow}")"
        justification="$(jq -r '.justification' <<< "${flow}")"
        src_set="$(zone_set_name "${src_zone}")"
        dst_set="$(zone_set_name "${dst_zone}")"
        echo "        # ${justification}"
        echo "        ip saddr @${src_set}_net ip daddr @${dst_set}_net ${proto} dport ${dport} accept"
    done
 
    echo "        log prefix \"meddefense-forward-drop: \" drop"
    echo "    }"
    echo ""
 
    # --- output chain: policy accept, explicit drops for zones this host
    #     must not send outbound to (deny_all pairs where src_zone == HOST_ZONE) ---
    echo "    chain output {"
    echo "        type filter hook output priority 0; policy accept;"
 
    mapfile -t OUTPUT_DENIES < <(jq -c --arg hz "${HOST_ZONE}" '.deny_all[] | select(.src_zone == $hz)' "${RULES_PATH}")
    for deny in "${OUTPUT_DENIES[@]}"; do
        dst_zone="$(jq -r '.dst_zone' <<< "${deny}")"
        dst_set="$(zone_set_name "${dst_zone}")"
        echo "        ip daddr @${dst_set}_net log prefix \"meddefense-output-drop: \" drop"
    done
 
    echo "    }"
    echo ""
    echo "}"
} > "${CONF_TMP}"
 
mv "${CONF_TMP}" "${CONF_PATH}"
chmod 644 "${CONF_PATH}"
echo "    $(wc -l < "${CONF_PATH}") lines rendered."
 
# ---------------------------------------------------------------------------
# MANDATORY gate: check-only parse. Nothing further happens if this fails.
# ---------------------------------------------------------------------------
echo "[*] Validating syntax (nft -c -f, check-only, applies nothing)..."
check_output_file="$(mktemp)"
if ! nft -c -f "${CONF_PATH}" > "${check_output_file}" 2>&1; then
    echo "FAILED: nftables.conf does not parse cleanly. Nothing was touched on the live ruleset." >&2
    cat "${check_output_file}" >&2
    rm -f "${check_output_file}"
    exit 1
fi
rm -f "${check_output_file}"
echo "    OK - syntax valid."
 
# ---------------------------------------------------------------------------
# 3. Back up the current live ruleset before touching anything.
# ---------------------------------------------------------------------------
mkdir -p "${BACKUP_DIR}" 2>/dev/null || true
backup_timestamp="$(date -u +"%Y%m%dT%H%M%SZ")"
backup_path="${BACKUP_DIR}/nftables-rollback-${backup_timestamp}.nft"
 
echo "[*] Backing up current ruleset to ${backup_path}..."
# Prefixing the backup with an explicit "flush ruleset" is critical: if
# the live ruleset was already empty at backup time, `nft list ruleset`
# alone produces an empty file, and loading an empty file with `nft -f`
# later applies zero instructions - it does NOT clear whatever new
# ruleset is active by then. Found the hard way on billing-srv-01: the
# backup was empty, `nft -f <empty backup>` after a lockout did nothing,
# and only an explicit `nft flush ruleset` actually restored access. The
# flush line makes this backup file self-sufficient as a real rollback
# regardless of what the live ruleset looked like when it was captured.
{
    echo "flush ruleset"
    nft list ruleset 2>/dev/null
} > "${backup_path}"
if [[ ! -s "${backup_path}" ]]; then
    echo "FAILED: could not back up the current ruleset. Refusing to apply without a rollback path." >&2
    exit 1
fi
echo "    OK ($(wc -l < "${backup_path}") lines backed up, including the leading flush)."
 
# ---------------------------------------------------------------------------
# Safety net: schedule an automatic, unattended rollback that fires on its
# own after ROLLBACK_TIMEOUT_SECONDS unless explicitly cancelled below.
# This is the standard safety pattern for exactly the risk this task's own
# instructions describe ("a wrong atomic ruleset update can lock you out
# of your own SSH session in one second") - prefers `at` if available,
# falls back to a detached background timer otherwise.
# ---------------------------------------------------------------------------
rollback_job_id=""
rollback_pid=""
 
schedule_rollback() {
    if command -v at >/dev/null 2>&1; then
        rollback_job_id="$(echo "nft -f '${backup_path}'" | at now + "$(( (ROLLBACK_TIMEOUT_SECONDS + 59) / 60 ))" minutes 2>&1 | grep -oP 'job \K[0-9]+' || true)"
    fi
    if [[ -z "${rollback_job_id}" ]]; then
        ( sleep "${ROLLBACK_TIMEOUT_SECONDS}"; nft -f "${backup_path}" >/dev/null 2>&1 ) &
        disown
        rollback_pid=$!
    fi
}
 
cancel_rollback() {
    if [[ -n "${rollback_job_id}" ]] && command -v atrm >/dev/null 2>&1; then
        atrm "${rollback_job_id}" >/dev/null 2>&1 || true
    elif [[ -n "${rollback_pid}" ]]; then
        kill "${rollback_pid}" >/dev/null 2>&1 || true
    fi
}
 
echo "[*] Arming automatic rollback safety net (fires in ${ROLLBACK_TIMEOUT_SECONDS}s unless cancelled after successful verification)..."
schedule_rollback
 
# ---------------------------------------------------------------------------
# 4. Apply the new ruleset atomically.
# ---------------------------------------------------------------------------
echo "[*] Applying new ruleset (nft -f)..."
apply_output_file="$(mktemp)"
if ! nft -f "${CONF_PATH}" > "${apply_output_file}" 2>&1; then
    echo "FAILED to apply. Reverting immediately from backup..." >&2
    cat "${apply_output_file}" >&2
    nft -f "${backup_path}" >/dev/null 2>&1 || true
    cancel_rollback
    rm -f "${apply_output_file}"
    exit 1
fi
rm -f "${apply_output_file}"
echo "    Applied."
 
# ---------------------------------------------------------------------------
# 5. Verify the load and count rules.
# ---------------------------------------------------------------------------
echo "[*] Verifying (nft list ruleset)..."
live_ruleset="$(nft list ruleset 2>/dev/null || true)"
actual_rule_count="$(grep -c "accept\|drop\|reject" <<< "${live_ruleset}" || true)"
expected_rule_count="$(grep -c "accept\|drop\|reject" "${CONF_PATH}" || true)"
 
verified="false"
if [[ "${actual_rule_count}" -eq "${expected_rule_count}" ]] && grep -q "table inet meddefense" <<< "${live_ruleset}"; then
    verified="true"
    echo "    OK - ${actual_rule_count}/${expected_rule_count} rules present, table inet meddefense confirmed live."
    echo "[*] Verification passed - cancelling the automatic rollback safety net."
    cancel_rollback
else
    echo "    MISMATCH - expected ${expected_rule_count} rules, found ${actual_rule_count}. Leaving the automatic rollback armed - it will revert in up to ${ROLLBACK_TIMEOUT_SECONDS}s unless you investigate and cancel it yourself." >&2
fi
 
# ---------------------------------------------------------------------------
# Emit a small JSON evidence record of this transition (this project's own
# rule: JSON is the deliverable format for every validation/tracking task).
# ---------------------------------------------------------------------------
jq -n \
    --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    --arg host_zone "${HOST_ZONE}" \
    --arg backup_path "${backup_path}" \
    --argjson expected_rules "${expected_rule_count:-0}" \
    --argjson actual_rules "${actual_rule_count:-0}" \
    --argjson verified "${verified}" \
    --argjson rollback_timeout "${ROLLBACK_TIMEOUT_SECONDS}" \
    '{timestamp: $timestamp, host_zone: $host_zone, backup_path: $backup_path,
      expected_rules: $expected_rules, actual_rules: $actual_rules,
      verified: $verified, rollback_timeout_seconds: $rollback_timeout}' > "${APPLY_LOG_PATH}"
 
echo "Report saved to: $(basename "${APPLY_LOG_PATH}")"
 
if [[ "${verified}" == "true" ]]; then
    exit 0
else
    exit 1
fi
